[project]
name = 'NFT-student-art-gallery'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.student-art-nft]
path = 'contracts/student-art-nft.clar'
clarity_version = 3
epoch = 3.0
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
